account/urls.py
# The views used below are normally mapped in django.contrib.admin.urls.py
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path, include
from . import views as Function

app_name = "account"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('', Function.home, name='home'),
    path('picture/', Function.picture, name='picture'),
    path('post/<int:pk>/', Function.post, name='post'),
    path('lazy_load_posts/', Function.lazy_load_posts, name='lazy_load_posts'),
    path('logout/', Function.logout_view, name='logout'),
    path('addpicture/', Function.addPicture, name='addPicture'),
    path('addcv/', Function.addCv, name='addCv'),
    path('addsafepayment/<str:username>/',
         Function.addSafePayment, name='addSafePayment'),
    path('addSafePaymentOrder/<int:pk>/',
         Function.addSafePaymentOrder, name='addSafePaymentOrder'),
    path('deletecv/<int:pk>/', Function.deleteCv, name='deleteCv'),
    path('deleteservice/<int:pk>/', Function.deleteService, name='deleteService'),
    path('setting/', Function.profile, name='setting'),
    path('message/', Function.message, name='message'),
    path('message/<str:username>/', Function.message, name='messageUser'),
    path('register/', Function.register, name='register'),
    # path('OrderViews/', Function.OrderViews, name='OrderViews'),
    path('operate/', include('accounting.urls'), name="accounting"),
    path('addService/', Function.addService, name='addService'),
    path('LikePost/', Function.LikePost, name='LikePost'),
    path('follow/', Function.follow, name='follow'),
    path('follow/<str:username>/', Function.follow, name='follow_User'),
    path('p/<str:slug>/checkout/', Function.checkoutUser, name="checkoutUser"),
    path('p/<str:slug>/checkout/<int:service>/',
         Function.checkoutUser, name="checkoutUserService"),
    path('desk/', Function.desk, name="desk"),
    path('notification/', Function.notification, name="notification"),
    path('orders/', Function.orders, name="orders"),
    path('ordersTrue/<int:pk>/', Function.ordersTrue, name="ordersTrue"),
    path('ordersFalse/<int:pk>/', Function.ordersFalse, name="ordersFalse"),
    path('listSafePayment/', Function.listSafePayment, name="listSafePayment"),
    path('listDispute/', Function.listDispute, name="listDispute"),
    path('addDispute/<int:pk>/', Function.addDispute, name="addDispute"),
    path('SafePaymentRefuse/<int:pk>/',
         Function.SafePaymentRefuse, name="SafePaymentRefuse"),
    path('SafePaymentAccept/<int:pk>/',
         Function.SafePaymentAccept, name="SafePaymentAccept"),
    path('createSafePayment/<int:pk_request>/<int:pk_accept>/',
         Function.createSafePayment, name="createSafePayment"),
    path('addRequest/', Function.addRequest, name="addRequest"),
    path('addAcceptRequest/<int:pk>/',
         Function.addAcceptRequest, name="addAcceptRequest"),
    path('projectManagement/<int:pk>/',
         Function.projectManagement, name="projectManagement"),
    path('DeleteProjectManagement/<int:pk>/',
         Function.deleteSubsetTrello, name="deleteSubsetTrello"),
    path('DeleteProjectManagementMain/<int:pk>/',
         Function.deleteTrello, name="deleteTrello"),
    path('AddSubsetProjectManagement/<int:pk>/',
         Function.AddSubsetProjectManagement, name="AddSubsetProjectManagement"),
    path('AddProjectManagement/<int:pk>/',
         Function.AddProjectManagement, name="AddProjectManagement"),
    path('numberOfFollowers/<str:username>/',
         Function.numberOfFollowers, name="numberOfFollowers"),
    path('numberOfFollowing/<str:username>/',
         Function.numberOfFollowing, name="numberOfFollowing"),

    # path('change_picture/<int:pk>', change_picture, name='change-picture'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),


]

api/urls.py
from django.urls import  include, path,re_path
from . import views
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth import views as auth_view


router = routers.SimpleRouter()
router.register(r'HomeApiView', views.HomeApiView, basename="HomeApiView")


urlpatterns = [
# urls.py
     path('social/google/', include("social_django.urls", namespace='social')),
     path('blog/', include('blog.urls')),
     path('login/', auth_view.LoginView.as_view(), name='login'),
     path('token/', obtain_auth_token),
     path('CheckToken/', views.CheckToken.as_view(), name="CheckToken"),
     # path('token/', TokenObtainPairView.as_view(),name='token_obtain_pair'),
     # path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
     path('ExploreApiView/', views.ExploreApiView.as_view(), name="ExploreApiView"),
     path('ExploreProjectApiView/', views.ExploreProjectApiView.as_view(),
          name="ExploreProjectApiView"),
     path('AddLikeView/', views.AddLikeView.as_view(), name="AddLikeView"),
     path('MassageApi/', views.MassageApi.as_view(), name="MassageApi"),
     path('AllMassageApi/', views.AllMassageApi.as_view(), name="AllMassageApi"),
     path('FollowUnfollowApi/<str:username>/',
          views.FollowUnfollowApi.as_view(), name="FollowUnfollowApi"),



     # get data like this ?&min_price=50001&max_price=80000&search=logo&ordering=-price


     path('PicturePostDestroyRetrive/<int:pk>/',
          views.PicturePostDestroyRetrive.as_view(), name="PicturePostDestroyRetrive"),
     path('RequestPostDestroyRetrive/<int:pk>/',
          views.RequestPostDestroyRetrive.as_view(), name="RequestPostDestroyRetrive"),
     path('AddAcceptRequestApi/<int:pk>/',
          views.AddAcceptRequestApi.as_view(), name="AddAcceptRequestApi"),
     path('AddRequestApi/', views.AddRequestApi.as_view(), name="AddRequestApi"),
     path('RequestListApi/<str:username>/', views.RequestListApi.as_view(), name="RequestListApi"),
     path('DestroyRequestApi/<int:pk>/', views.DestroyRequestApi.as_view(), name="DestroyRequestApi"),
     path('RequestSearchApi/', views.RequestSearchApi.as_view(),name="RequestSearchApi"),
     path('PictureSearchApi/', views.PictureSearchApi.as_view(),
          name="PictureSearchApi"),
     path('UserSettingApi/',
          views.UserSettingApi.as_view(), name="UserSettingApi"),
     path('UserRetrieveApi/<str:username>/',
          views.UserRetrieveApi.as_view(), name="UserRetrieveApi"),
     path('UserSearchListApi/', views.UserSearchListApi.as_view(),
          name="UserSearchListApi"),
     path('AddPostPictureApi/', views.AddPostPictureApi.as_view(),
          name="AddPostPictureApi"),
     path('UserCreate/', views.UserCreate.as_view(), name="UserCreate"),
     path('NotificationApi/', views.NotificationApi.as_view(), name="NotificationApi"),
     path('CashApi/', views.CashApi.as_view(), name="CashApi"),
     path('PaymentWalletApi/', views.PaymentWalletApi.as_view(),
          name="PaymentWalletApi"),
     path('favoritesApi/<str:username>/',
          views.favoritesApi.as_view(), name="favoritesApi"),
     path('SafePaymentApi/', views.SafePaymentApi.as_view(), name="SafePaymentApi"),
     path('TrelloApi/<int:pk>/', views.TrelloApi.as_view(), name="TrelloApi"),
     path('SubsetTrelloDestroyApi/<int:pk>/',
          views.SubsetTrelloDestroyApi.as_view(), name="SubsetTrelloDestroyApi"),
     path('DisputeApi/', views.DisputeApi.as_view(), name="DisputeApi"),
     path('DisputeDestroyApi/<int:pk>/',
          views.DisputeDestroyApi.as_view(), name="DisputeDestroyApi"),
     path('AddDisputeApi/',
          views.AddDisputeApi.as_view(), name="AddDisputeApi"),
     path('OrderApi/', views.OrderApi.as_view(), name="OrderApi"),
     path('AddOrderApi/<str:username>/', views.AddOrderApi.as_view(), name="AddOrderApi"),
     path('OrderTrueApi/',
          views.OrderTrueApi.as_view(), name="OrderTrueApi"),
     path('OrderFalseApi/',
          views.OrderFalseApi.as_view(), name="OrderFalseApi"),
     path('CountReadStatus/', views.CountReadStatus.as_view(), name="CountReadStatus"),
     path('PicturePostListApi/<str:username>/',
          views.PicturePostListApi.as_view(), name="PicturePostListApi"),
     path('ListUserMessageApi/', views.ListUserMessageApi.as_view(),
          name="ListUserMessageApi"),
     path('DeskApi/', views.DeskApi.as_view(),name="DeskApi"),
     path('AcceptSafePaymentApi/', views.AcceptSafePaymentApi.as_view(),name="AcceptSafePaymentApi"),
     path('RefuseSafePaymentApi/', views.RefuseSafePaymentApi.as_view(),name="RefuseSafePaymentApi"),
     path('RulesListApi/', views.RulesListApi.as_view(),name="RulesListApi"),
     path('SpamCreateApi/', views.SpamCreateApi.as_view(),name="SpamCreateApi"),
     path('UserSuggestion/', views.User_suggestion.as_view(),name="User_suggestion"),
     path('Send_code/', views.Send_code.as_view(),name="Send_code"),
     path('Code_check/', views.Code_check.as_view(),name="Code_check"),
     path('PostTagApi/', views.PostTagApi.as_view(),name="PostTagApi"),
     path('following/', views.following.as_view(),name="following"),
     path('followingList/', views.followingList.as_view(),name="followingList"),
     path('followersList/', views.followersList.as_view(),name="followersList"),
     path('ContactApi/', views.ContactApi.as_view(),name="ContactApi"),
]

urlpatterns += router.urls

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from . import views
from account.views import cv, service, favourites

app_name="main"
urlpatterns = [
    path('', views.index,name="main"),
    path('explore/', views.explore,name="explore"),
    path('explore/lazy_load_posts/', views.lazyLoadExplore,name="lazy_load_posts"),
    path('contact/', views.Contact,name="contact"),
    path('p/<str:slug>/', views.profile , name="profile"),
    path('p/<str:slug>/cv', cv, name="cv"),
    path('p/<str:slug>/service', service , name="service"),
    path('p/<str:slug>/favourites', favourites, name="favourites"),
    path('search/', views.search , name="search"),
    path('Rules/', views.rules, name="Rules"),
    path('request/<int:pk>/', views.requestUser, name="request"),

]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/profile/cv.html
{% load define_action %} {% load static %}
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="{% static 'inside/images/favicon.png' %}" rel="icon" type="image/png">

    <!-- Basic Page Needs
    ================================================== -->
    <title>خدمات</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="تریگت - شبکه ی بازار خدمات آنلاین">
    <link rel="stylesheet" href="{% static 'inside/css/cv.css' %}?v=001"> {% include "include/header.html" %}




</head>

<body>


    <div id="wrapper">

        {% include "include/sidebar.html" %}

        <div class="main_content">

            {% include "include/mainHeader.html" %}

            <div class="container pro-container m-auto">
                {% include "include/downNavbar.html" %}

                <!-- profile-cover-->
                {% include "include/container.html" %}
                <div class="d-flex flex-row-reverse align-items-center px-3 pt-4">
                    <div class="bg-primary  rounded-lg" style="height:30px;padding:1.6px;padding-top:3px;background-image: linear-gradient(#FF3600, #FFA38B);"></div>
                    <p class="irsa text-lg px-3">رزومه</p>
                </div>

                <!-- edith1 open -->
                {% if cv %}
                <div class="container-fluid col 10">
                    <div class="container col-8 ">

                        <ul class="timeline w-full">
                            {% for result in cv %}
                            <li>
                                <div class="direction-l ">
                                    <div class="flag-wrapper">
                                        {% if result.title %}<span class=" irsa">{{ result.title }}</span>{% endif %}
                                        <span class="time-wrapper irsa">{% if request.user == user %} <a href="{% url "account:deleteCv" result.pk %}" class="p-2">حذف</a> {% endif %}<span class="time text-muted">{% if result.start %}{{ result.JSpublish.0 }}/{{ result.JSpublish.1 }}  <br/>{% endif %} {% if result.end and result.start %}{{ result.JEpublish.0 }}/{{ result.JEpublish.1 }} {% endif %}</span></span>

                                    </div>
                                    <div class="flag shadow-1 border-top1 p-2 m-2 flex-fill bg-white rounded-lg irsa">
                                        <div class="p-2">{{ result.body }}</div>
                                    </div>
                            </li>
                            {% endfor %}


                        </ul>



                        </div>
                    </div>
                    {% else %} {% include "include/empty.html" %} {% endif %}
                </div>

            </div>





            <!-- Scripts
    ================================================== -->
            {% include "include/footer.html" %}

</body>



</html>

templates/profile/favourites.html
{% load define_action %}
{% load jalali %}
{% load static %}
<!DOCTYPE html>
<html lang="en">




<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="{% static 'inside/images/favicon.png' %}" rel="icon" type="image/png">

    <!-- Basic Page Needs
    ================================================== -->
    <title>مورد علاقه</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="تریگت - شبکه ی بازار خدمات آنلاین">

{% include "include/header.html" %}

    <style>
        @media (min-width: 1024px) {
            header .header_inner {
                max-width: 980px;
            }
            .pro-container {
                max-width: 860px;
            }
        }

    </style>


</head>

<body >


    <div id="wrapper">

        {% include "include/sidebar.html" %}


        <div class="main_content" >

        {% include "include/mainHeader.html" %}

            <div class="container pro-container m-auto">
            {%  include "include/downNavbar.html" %}

                {% include "include/container.html" %}
                <div class="d-flex flex-row-reverse align-items-center px-3 pt-4">
                    <div class="bg-primary  rounded-lg" style="height:30px;padding:1.6px;padding-top:3px;background-image: linear-gradient(#FF3600, #FFA38B);"></div>
                    <p class="irsa text-lg px-3" >علایق</p>
                </div>
                {% if favourites %}
                <div class="my-6 mt-8 grid lg:grid-cols-4 grid-cols-2 gap-1.5 hover:text-yellow-700 uk-link-reset">
                 {% for picture in favourites %}
                    <a href="{% url "account:post" picture.pk %}">
                        <div class="bg-red-500 max-w-full lg:h-64 h-40 rounded-md relative overflow-hidden uk-transition-toggle" tabindex="0">
                            <img src="{{ picture.image.url }}" class="w-full h-full absolute object-cover inset-0">

                            <div  class="absolute bg-black bg-opacity-40 bottom-0 flex h-full items-center justify-center space-x-5 text-lg text-white uk-transition-scale-up w-full">
                                <div uk-toggle class="flex items-center irsa">
                                    <ion-icon name="pricetags" class="mr-1"></ion-icon> {{ picture.Jpublish.0 }}/{{ picture.Jpublish.1 }}/{{ picture.Jpublish.2 }} </div>
                            </div>

                        </div>
                    </a>
                    
                    {% endfor %}
                </div>
                {% else %}
                {% include "include/empty.html" %}
                {% endif %}


{#                <div class="flex justify-center mt-6">#}
{#                    <a href="#" class="bg-white dark:bg-gray-900 font-semibold my-3 px-6 py-2 rounded-full shadow-md dark:bg-gray-800 dark:text-white irsa"> بیشتر ..</a>#}
{#                </div>#}


            </div>

        </div>

    </div>





    <script>
        function shareLinkF(dataValue){
        let input = document.body.appendChild(document.createElement("input"));
        input.value = `${window.location.hostname}/p/${dataValue}`;
        input.focus();
        input.select();
        document.execCommand('copy');
        input.parentNode.removeChild(input);
        alert(`${window.location.hostname}/p/${dataValue} کپی شد.`)
    }
    function shareLinkP(dataValue){
        let input = document.body.appendChild(document.createElement("input"));
        input.value = `${window.location.hostname}/request/${dataValue}`;
        input.focus();
        input.select();
        document.execCommand('copy');
        input.parentNode.removeChild(input);
        alert(`${window.location.hostname}/request/${dataValue} کپی شد.`)
    }


    </script>


    <!-- Scripts
    ================================================== -->
    {% include "include/footer.html" %}

</body>



</html>

templates/profile/profile.html
{% load define_action %} {% load jalali %} {% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="{% static 'inside/images/favicon.png' %}" rel="icon" type="image/png">

    <!-- Basic Page Needs
    ================================================== -->
    <title>{{ user.get_full_name }} - تریگت</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Instello - Sharing Photos platform HTML Template"> {% include "include/header.html" %}

    <style>
        @media (min-width: 1024px) {
            header .header_inner {
                max-width: 980px;
            }
            .pro-container {
                max-width: 860px;
            }
        }
    </style>


</head>

<body>


    <div id="wrapper">

        {% include "include/sidebar.html" %}


        <div class="main_content" id="profile" value="{{ user.username }}">

            {% include "include/mainHeader.html" %}

            <div class="container pro-container  m-auto">
                {% include "include/downNavbar.html" %} {% include "include/container.html" %}
                <div class="d-flex flex-row-reverse align-items-center px-3 pt-4">
                    <div class="bg-primary  rounded-lg" style="height:30px;padding:1.6px;padding-top:3px;background-image: linear-gradient(#FF3600, #FFA38B);"></div>
                    <p class="irsa text-lg px-3">{% if user.ServiceProvider == True %}نمونه کار ها{% else %}پروژه ها {% endif %}</p>
                </div>
                {% if user.ServiceProvider == True %} {% if pictures %}

                <div class="d-flex flex-column align-items-center" v-if="loading">
                    <img src="{% static 'vue/image/loading.gif' %}" alt="loading" style="width: 40px;" />
                </div>
                <div class="uk-child-width-1-2 uk-child-width-1-3@m uk-grid-small my-5" uk-grid="masonry: true" v-else>
                    <a v-bind:href="'/account/post/'+ item.id" v-for="item in picture">
                        <img v-bind:src="item.image" class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle rounded-md" style="height:auto;width:100%;">
                    </a>
                </div>
                {% else %} {% include "include/empty.html" %} {% endif %} {% else %}
                <div class="grid  mt-12 gap-8 row">
                    {% for result in RequestServices %}
                    <div class="bg-white rounded-md lg:shadow-lg shadow  rtl">
                        <div class="flex justify-between items-center px-4 py-3 mt-3 rounded-lg bg-gray-100">
                            <div class="flex flex-1 items-center space-x-4">

                                <p class="irsa px-2">{% jalali result.createdAdd as dateResult %}{{ dateResult.0 }}/{{ dateResult.1 }}/{{ dateResult.2 }}</p>
                                <P class="px-3 py-2 irsa bg-white  rounded-lg"> قیمت {{ result.price }} تومان</P>


                            </div>
                            <div>
                                <a href="#"> <i class="icon-feather-more-horizontal text-2xl hover:bg-gray-200 rounded-full p-2 transition -mr-1 dark:hover:bg-gray-700"></i> </a>
                                <div class="bg-white w-56 shadow-md mx-auto p-2 mt-12 rounded-md text-gray-500 hidden text-base border border-gray-100 dark:bg-gray-900 dark:text-gray-100 dark:border-gray-700" uk-drop="mode: hover;pos: top-right">

                                    <ul class="rtl space-y-1">
                                        <li>
                                            <button href="#" onclick="shareLink('request/{{ result.pk }}')" class="shareLink irsa flex items-center px-3 py-2 hover:bg-gray-200 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                                    <i class="uil-share-alt mr-1"></i> اشتراک گذاری
                                                </button>
                                        </li>
                                        {% if result.author == request.user %}
                                        <li>
                                            <hr class="-mx-2 my-2 dark:border-gray-800">
                                        </li>
                                        <li>
                                            <form action="" method="POST" class="irsa flex items-center px-3 py-2 text-red-500 hover:bg-red-100 hover:text-red-500 rounded-md dark:hover:bg-red-600">
                                                {% csrf_token %}
                                                <input type="hidden" name="flag" value="{{ result.pk }}" />

                                                <button type="submit" class="  irsa " /><i class="uil-trash-alt mr-1  mr-1 "></i> حذف<button>
                                                </form>
                                            </li>
                                            {% endif %}
                                        </ul>

                                    </div>
                                </div>
                            </div>
                            <a href="{% url "main:request" result.pk  %}" class="grid grid-cols-2 gap-3 lg:p-6 p-4">
                                <h2 class="irsa text-2xl">{{ result.title }}</h2>
                                <br>
                                <p class="irsa">{{ result.body }}</p>
                                <br>
                                <p class="irsa text-blue-400">{{ result.subcategories.count }} پیشنهاد</p>
                            </a>
                        </div>
                        {% empty %}
                                {% include "include/empty.html" %}
                    {% endfor %}
                    </div>
               {% endif %}

            </div>

        </div>

    </div>



    <script>
        function shareLinkF(dataValue){
        let input = document.body.appendChild(document.createElement("input"));
        input.value = `${window.location.hostname}/p/${dataValue}`;
        input.focus();
        input.select();
        document.execCommand('copy');
        input.parentNode.removeChild(input);
        alert(`${window.location.hostname}/p/${dataValue} کپی شد.`)
    }
    function shareLinkP(dataValue){
        let input = document.body.appendChild(document.createElement("input"));
        input.value = `${window.location.hostname}/request/${dataValue}`;
        input.focus();
        input.select();
        document.execCommand('copy');
        input.parentNode.removeChild(input);
        alert(`${window.location.hostname}/request/${dataValue} کپی شد.`)
    }


    </script>


    <!-- Scripts
    ================================================== -->
    {% include "include/footer.html" %}
    
    <script src="{% static "vue/js/profile.js" %}"></script>


</body>



</html>