api/urls.py
from django.urls import  include, path,re_path
from . import views
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth import views as auth_view


router = routers.SimpleRouter()
router.register(r'HomeApiView', views.HomeApiView, basename="HomeApiView")


urlpatterns = [
# urls.py
     path('social/google/', include("social_django.urls", namespace='social')),
     path('blog/', include('blog.urls')),
     path('login/', auth_view.LoginView.as_view(), name='login'),
     path('token/', obtain_auth_token),
     path('CheckToken/', views.CheckToken.as_view(), name="CheckToken"),
     # path('token/', TokenObtainPairView.as_view(),name='token_obtain_pair'),
     # path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
     path('ExploreApiView/', views.ExploreApiView.as_view(), name="ExploreApiView"),
     path('ExploreProjectApiView/', views.ExploreProjectApiView.as_view(),
          name="ExploreProjectApiView"),
     path('AddLikeView/', views.AddLikeView.as_view(), name="AddLikeView"),
     path('MassageApi/', views.MassageApi.as_view(), name="MassageApi"),
     path('AllMassageApi/', views.AllMassageApi.as_view(), name="AllMassageApi"),
     path('FollowUnfollowApi/<str:username>/',
          views.FollowUnfollowApi.as_view(), name="FollowUnfollowApi"),



     # get data like this ?&min_price=50001&max_price=80000&search=logo&ordering=-price


     path('PicturePostDestroyRetrive/<int:pk>/',
          views.PicturePostDestroyRetrive.as_view(), name="PicturePostDestroyRetrive"),
     path('RequestPostDestroyRetrive/<int:pk>/',
          views.RequestPostDestroyRetrive.as_view(), name="RequestPostDestroyRetrive"),
     path('AddAcceptRequestApi/<int:pk>/',
          views.AddAcceptRequestApi.as_view(), name="AddAcceptRequestApi"),
     path('AddRequestApi/', views.AddRequestApi.as_view(), name="AddRequestApi"),
     path('RequestListApi/<str:username>/', views.RequestListApi.as_view(), name="RequestListApi"),
     path('DestroyRequestApi/<int:pk>/', views.DestroyRequestApi.as_view(), name="DestroyRequestApi"),
     path('RequestSearchApi/', views.RequestSearchApi.as_view(),name="RequestSearchApi"),
     path('PictureSearchApi/', views.PictureSearchApi.as_view(),
          name="PictureSearchApi"),
     path('UserSettingApi/',
          views.UserSettingApi.as_view(), name="UserSettingApi"),
     path('UserRetrieveApi/<str:username>/',
          views.UserRetrieveApi.as_view(), name="UserRetrieveApi"),
     path('UserSearchListApi/', views.UserSearchListApi.as_view(),
          name="UserSearchListApi"),
     path('AddPostPictureApi/', views.AddPostPictureApi.as_view(),
          name="AddPostPictureApi"),
     path('UserCreate/', views.UserCreate.as_view(), name="UserCreate"),
     path('NotificationApi/', views.NotificationApi.as_view(), name="NotificationApi"),
     path('CashApi/', views.CashApi.as_view(), name="CashApi"),
     path('PaymentWalletApi/', views.PaymentWalletApi.as_view(),
          name="PaymentWalletApi"),
     path('favoritesApi/<str:username>/',
          views.favoritesApi.as_view(), name="favoritesApi"),
     path('SafePaymentApi/', views.SafePaymentApi.as_view(), name="SafePaymentApi"),
     path('TrelloApi/<int:pk>/', views.TrelloApi.as_view(), name="TrelloApi"),
     path('SubsetTrelloDestroyApi/<int:pk>/',
          views.SubsetTrelloDestroyApi.as_view(), name="SubsetTrelloDestroyApi"),
     path('DisputeApi/', views.DisputeApi.as_view(), name="DisputeApi"),
     path('DisputeDestroyApi/<int:pk>/',
          views.DisputeDestroyApi.as_view(), name="DisputeDestroyApi"),
     path('AddDisputeApi/',
          views.AddDisputeApi.as_view(), name="AddDisputeApi"),
     path('OrderApi/', views.OrderApi.as_view(), name="OrderApi"),
     path('AddOrderApi/<str:username>/', views.AddOrderApi.as_view(), name="AddOrderApi"),
     path('OrderTrueApi/',
          views.OrderTrueApi.as_view(), name="OrderTrueApi"),
     path('OrderFalseApi/',
          views.OrderFalseApi.as_view(), name="OrderFalseApi"),
     path('CountReadStatus/', views.CountReadStatus.as_view(), name="CountReadStatus"),
     path('PicturePostListApi/<str:username>/',
          views.PicturePostListApi.as_view(), name="PicturePostListApi"),
     path('ListUserMessageApi/', views.ListUserMessageApi.as_view(),
          name="ListUserMessageApi"),
     path('DeskApi/', views.DeskApi.as_view(),name="DeskApi"),
     path('AcceptSafePaymentApi/', views.AcceptSafePaymentApi.as_view(),name="AcceptSafePaymentApi"),
     path('RefuseSafePaymentApi/', views.RefuseSafePaymentApi.as_view(),name="RefuseSafePaymentApi"),
     path('RulesListApi/', views.RulesListApi.as_view(),name="RulesListApi"),
     path('SpamCreateApi/', views.SpamCreateApi.as_view(),name="SpamCreateApi"),
     path('UserSuggestion/', views.User_suggestion.as_view(),name="User_suggestion"),
     path('Send_code/', views.Send_code.as_view(),name="Send_code"),
     path('Code_check/', views.Code_check.as_view(),name="Code_check"),
     path('PostTagApi/', views.PostTagApi.as_view(),name="PostTagApi"),
     path('following/', views.following.as_view(),name="following"),
     path('followingList/', views.followingList.as_view(),name="followingList"),
     path('followersList/', views.followersList.as_view(),name="followersList"),
     path('ContactApi/', views.ContactApi.as_view(),name="ContactApi"),
]

urlpatterns += router.urls

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from . import views
from account.views import cv, service, favourites

app_name="main"
urlpatterns = [
    path('', views.index,name="main"),
    path('explore/', views.explore,name="explore"),
    path('explore/lazy_load_posts/', views.lazyLoadExplore,name="lazy_load_posts"),
    path('contact/', views.Contact,name="contact"),
    path('p/<str:slug>/', views.profile , name="profile"),
    path('p/<str:slug>/cv', cv, name="cv"),
    path('p/<str:slug>/service', service , name="service"),
    path('p/<str:slug>/favourites', favourites, name="favourites"),
    path('search/', views.search , name="search"),
    path('Rules/', views.rules, name="Rules"),
    path('request/<int:pk>/', views.requestUser, name="request"),

]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


main/models.py
from django.db import models
from django.utils.html import format_html
from account.models import User
from django.utils import timezone
from extensions.utils import jalali_converter
from PIL import Image


# Create your models here.


class Category(models.Model):
    title = models.TextField(blank=True, null=True, verbose_name="ویژگی")
    position = models.IntegerField(
        verbose_name="پوزیشن", blank=True, null=True)
    createdadd = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ["-createdadd"]

    def __str__(self):
        return self.title


class IPAddress(models.Model):
    # title = models.TextField(verbose_name="تیتر")
    ip_address = models.TextField(verbose_name="آدرس آی پی")


class Attributes(models.Model):
    Property = models.TextField(blank=True, null=True, verbose_name="ویژگی")
    position = models.IntegerField(
        verbose_name="پوزیشن", blank=True, null=True)

    class Meta:
        verbose_name = "ویژگی محصول"
        verbose_name_plural = "ویژگی های محصول"
        ordering = ["position"]

    def __str__(self):
        return self.Property


class Price(models.Model):
    PRICETYPE_CHOICE = (("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"))
    title = models.TextField(verbose_name="تیتر")
    titleEN = models.SlugField(max_length=50, verbose_name="url تیتر")
    price = models.TextField(blank=True, null=True, verbose_name="قیمت")
    position = models.IntegerField(verbose_name="پوزیشن")
    category = models.ManyToManyField(
        Attributes, verbose_name="امکاناتی که دارد", related_name="T")
    category2 = models.ManyToManyField(
        Attributes, verbose_name="امکاناتی که ندارد", related_name="F")
    PriceType = models.CharField(max_length=1, choices=PRICETYPE_CHOICE, blank=True, null=True,
                                 verbose_name="عضو کدام محصول است؟")

    class Meta:
        verbose_name = "قیمت"
        verbose_name_plural = "قیمت ها"
        ordering = ["position"]

    def __str__(self):
        return self.title


class PostTag(models.Model):
    STATUS_CHOICES = (("p", "منتششر شده"), ("d", "پیشنویس شده"))
    TYPE_CHOICES = (("g", "گرافیک طراحی"), ("f", "فیلم و تیزر تبلیغاتی"), ("p", "عکاسی صنعتی"), ("o", "طراحی آفیس"),
                    ("w", "طراحی سایت"), ("s", "نرم افزار"), ("b", "ربات"), ("n", "شبکه و امنیت"))
    title = models.CharField(max_length=50, verbose_name="تیتر")
    question = models.TextField(verbose_name="سوال", blank=True, null=True)
    body = models.TextField(verbose_name="پاسخ", blank=True, null=True)
    position = models.IntegerField(verbose_name="پوزیشن")
    slug = models.SlugField(max_length=50, verbose_name="url مطلب")
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default="P", verbose_name="وضعیت محصول")
    category = models.ManyToManyField(Price, verbose_name="قیمت", blank=True)
    TypeProduct = models.CharField(max_length=1, choices=TYPE_CHOICES, blank=True, null=True,
                                   verbose_name="وضعیت محصول")

    symbol = models.TextField(verbose_name="نماد", blank=True, null=True)

    class Meta:
        verbose_name = "محصول"
        verbose_name_plural = "محصولات"
        ordering = ["position"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/studioconfig/{self.slug}/'


class Picture(models.Model):
    STATUS_CHOICES = (("p", "منتششر شده"), ("d", "پیشنویس شده"))
    category = models.ManyToManyField(
        PostTag, verbose_name="دسته بندی محصول", blank=True)
    like = models.ManyToManyField(
        User, verbose_name="تعداد لایک ها", blank=True, related_name="like_Picture")
    Visitor = models.ManyToManyField(
        User, verbose_name="بازدیده کننده", blank=True, related_name="Visitor_Picture")
    alt = models.CharField(blank=True, null=True,
                           max_length=200, verbose_name="تیتر")
    createdAdd = models.DateField(auto_now_add=True)
    position = models.IntegerField(
        default=1, blank=True, null=True, verbose_name="پوزیشن")
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default="p", verbose_name="وضعیت محصول")
    image = models.ImageField(upload_to="images", verbose_name="عکس محصول")
    author = models.ForeignKey(User, verbose_name="طراح", on_delete=models.SET_NULL, null=True,
                               related_name="author_Picture")

    class Meta:
        verbose_name = "عکس"
        verbose_name_plural = "عکس ها"
        # ordering = ("-position", "-createdAdd")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 800:
            img.thumbnail((800, 800))
            img.save(self.image.path)

    def picture_show(self):
        return format_html("<img src='{}' width=100 style='border-radius : 10px;' >".format(self.image.url))

    def Jpublish(self):
        return jalali_converter(self.createdAdd)


class OrderUser(models.Model):
    author = models.ForeignKey(User, verbose_name="نویسنده",
                               on_delete=models.SET_NULL, related_name="authorOrderUser", null=True)
    title = models.CharField(
        max_length=300, verbose_name="محصول درخواستی", blank=True, null=True)
    body = models.TextField(
        verbose_name="توضیحات محصول", blank=True, null=True)   
    optionsServiceMain= models.ManyToManyField("profile_items.ServiceOptionMain",blank=True,related_name="ServiceOptionslastOrder",verbose_name="آپشن ها")

    createdAdd = models.DateField(auto_now_add=True)
    service = models.ForeignKey("profile_items.Services", verbose_name="نوع خدمات",
                                on_delete=models.SET_NULL, related_name="serviceOrderUser", null=True)
    designer = models.ForeignKey(User, verbose_name="طراح", on_delete=models.SET_NULL, null=True,
                                 related_name="designerOrderUser")
    price = models.BigIntegerField(verbose_name="قیمت")
    accept = models.BooleanField(verbose_name="تایید", blank=True, null=True)
    safePayment = models.ForeignKey("main.SafePayment", verbose_name="نوع خدمات", on_delete=models.SET_NULL,
                                    related_name="serviceOrderUser", null=True, blank=True)

    class Meta:
        verbose_name = "پیام سفارش از طراح"
        verbose_name_plural = "پیام های سفارش از طراح"
        ordering = ["-createdAdd"]


class contact(models.Model):
    name = models.CharField(max_length=200, verbose_name="نام ونام خانوادگی")
    email = models.CharField(max_length=200, verbose_name="ایمیل")
    body = models.TextField(verbose_name="متن")
    createdadd = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "پیام ارتباط با ما"
        verbose_name_plural = "پیام های ارتباط با ما"
        ordering = ["-createdadd"]

   


class BuyStudio(models.Model):
    name = models.CharField(max_length=200, verbose_name="نام و نام خانوادگی")
    number = models.CharField(max_length=200, verbose_name="شماره ی تماس شما")
    image = models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name="نمونه کار های مد نظر شما", blank=True,
                             null=True)
    imageNeed = models.FileField(upload_to='uploads/%Y/%m/%d/', blank=True, null=True,
                                 verbose_name="فایل های مورد نیاز")
    body = models.TextField(
        verbose_name="توضیحات محصول", blank=True, null=True)
    createdadd = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "فرم خرید"
        verbose_name_plural = "فرم های خرید"
        ordering = ["-createdadd"]

    def __str__(self):
        return self.name


class FAQ(models.Model):
    TYPE_CHOICES = (("s", "استودیو "), ("p", "برنامه نویسی"),
                    ("m", "صفحه ی اصلی"), ("a", "اکانت"))
    TypeFAQ = models.CharField(
        max_length=1, choices=TYPE_CHOICES, blank=True, null=True, verbose_name="محل FAQ")
    title = models.CharField(max_length=300, verbose_name="تیتر FAQ")
    body = models.TextField(verbose_name="بدنه ی FAQ")
    createdadd = models.DateField(auto_now_add=True)
    position = models.IntegerField(
        blank=True, null=True, verbose_name="پوزیشن")

    class Meta:
        verbose_name = "فرم FAQ"
        verbose_name_plural = "فرم های FAQ"
        ordering = ["-createdadd"]

    def __str__(self):
        return self.title



class Blog(models.Model):
    createdadd = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, verbose_name="نویسنده", on_delete=models.SET_NULL, null=True,
                               related_name="BlogAuthor")
    title = models.CharField(max_length=200, verbose_name="موضوع")
    body = models.TextField(verbose_name="متن")
    image = models.ImageField(upload_to="images/Blog",
                              verbose_name="عکس ", blank=True, null=True)
    position = models.IntegerField(
        blank=True, null=True, verbose_name="پوزیشن")

    class Meta:
        verbose_name = "بلاگ"
        verbose_name_plural = "بلاگ ها"
        ordering = ["-createdadd"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        try:
            super().save(*args, **kwargs)
            img = Image.open(self.image.path)
            if img.height > 600:
                img.thumbnail((600, 600))
                img.save(self.image.path)
        except:
            pass


class Rules(models.Model):
    createdAdd = models.DateField(auto_now_add=True)
    position = models.IntegerField(
        verbose_name="پوزیشن", blank=True, null=True)

main/forms.py
from django import forms

from .models import contact,BuyStudio,OrderUser

class PostFormContact(forms.ModelForm):

    class Meta:
        model = contact
        fields = '__all__'

# class ProductFormContact(forms.Form):
#     name = forms.CharField(max_length=100)
#     body = forms.CharField(widget=forms.Textarea)
#     number = forms.CharField(max_length=15)


class ProductFormContact(forms.ModelForm):

    class Meta:
        model = BuyStudio
        fields = '__all__'

class OrderUserForm(forms.ModelForm):

    class Meta:
        model = OrderUser
        fields = '__all__'

templates/main/checkoutUser.html
{% load widget_tweaks %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link href="{% static 'inside/images/favicon.png' %}" rel="icon" type="image/png" />

    <!-- Basic Page Needs
    ================================================== -->
    <title>سفارش</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" /> {% include "include/header.html" %}
</head>

<body>
    <div id="wrapper">
        {% include "include/sidebar.html" %}

        <div class="main_content">
            {% include "include/mainHeader.html" %}

            <div class="container m-auto">
                {% include "include/downNavbar.html" %}

                <div class="grid mt-12 gap-8">
                    <form method="post" class="bg-white rounded-md  col-span-2">
                        {% csrf_token %}
                        <div class="grid grid-cols-1 gap-3 lg:p-6 p-4">
                            {% if service %}
                            <div>
                                <p class="irsa rtl">
                                    محصول درخواستی شما
                                    <span class="text-danger">{% if service.specialName %}{{ service.specialName }}{%else %}{{ service.nameProduct.title }}{% endif %}</span> {% if service.price %} با قیمت
                                    <span class="text-danger">{{ service.price }}</span> تومان {% endif %} است
                                </p>
                            </div>
                            {% if service.price %} {% else %}
                            <div>
                                <label for="id_price" class="irsa text-right"> قیمت</label> {% render_field form.price class="shadow-none bg-gray-100" %}
                            </div>

                            {% endif %} {% else %}
                            <div>
                                <label for="" class="irsa text-right"> محصول درخواستی</label> {% render_field form.title class="shadow-none bg-gray-100" required="on" %}
                            </div>
                            <div>
                                <label for="id_price" class="irsa text-right"> قیمت</label> {% render_field form.price class="shadow-none bg-gray-100" %}
                            </div>
                            {% endif %}
                            <div>
                                <label for="id_body" class="irsa text-right"> توضیحات</label> {% render_field form.body class="shadow-none bg-gray-100" %}
                            </div>
                        </div>
                        <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">

                            <button class="button bg-blue-700 irsa">ذخیره</button>
                        </div>
                    </form>
                </div>
                <div class="grid mt-12 gap-8">
                    <div class="bg-white rounded-md  col-span-2">
                        <div class="grid grid-cols-1 gap-3 text-center irsa lg:p-6 p-4">
                            درخواست شما به طراح ارسال خواهد شد و در صورت تایید درخواست طراح میتواند از طریق چت با شما در ارتباط باشد <br /> در صورت تایید درخواست شما توسط طراح ایمیلی به شما در رابطه با این موضوع زده خواهد شد
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Scripts
    ================================================== -->
    {% include "include/footer.html" %}
</body>

</html>

templates/main/enamad.html
<a referrerpolicy="origin" target="_blank" href="https://trustseal.enamad.ir/?id=215981&amp;Code=bxEKNoVWsgjvFYqTUtPG"><img referrerpolicy="origin" src="https://Trustseal.eNamad.ir/logo.aspx?id=215981&amp;Code=bxEKNoVWsgjvFYqTUtPG" alt="" style="cursor:pointer" id="bxEKNoVWsgjvFYqTUtPG"></a>
<div>پس از نمایش تصویر روی آن کلیک کنید</div>

templates/main/request.html
{% load jalali %} {% load static %}
<!DOCTYPE html>
<html lang="en">




<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="{% static 'inside/images/favicon.png' %}" rel="icon" type="image/png">

    <!-- Basic Page Needs
    ================================================== -->
    <title>درخواست</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="تریگت - شبکه ی بازار خدمات آنلاین"> {% include "include/header.html" %}
    <script type="text/javascript">
        window.CSRF_TOKEN = "{{ csrf_token }}";
    </script>
</head>

<body>
    <div id="wrapper">
        {% include "include/sidebar.html" %}
        <div class="main_content">
            {% include "include/mainHeader.html" %}
            <div class="container m-auto">
                {% include "include/downNavbar.html" %}
                <div class="lg:flex justify-center lg:space-x-10 lg:space-y-0 space-y-5">
                    <!-- left sidebar-->
                    <div class="space-y-5 flex-shrink-0 lg:w-7/12">
                        <div id="posts" class="space-y-5">
                            <div class="grid  mt-12 gap-8 row">
                                <div class="bg-white rounded-md shadow-1  rtl">
                                    <div class="flex justify-between items-center px-4 py-3 mt-3 rounded-lg bg-gray-100">
                                        <div class="flex flex-1 items-center space-x-4">
                                            <a href="{% url 'main:profile' result.author.username %}">
                                                <div class="mx-3    w-8 h-8 overflow-hidden " style="border-radius:10px;">
                                                    <img src="{% if result.author.image %}{{ result.author.image.url }}{% else %}{% static 'inside/avatar.jpg' %}{% endif %}" class="">
                                                </div>
                                            </a>
                                            <a href="{% url 'main:profile' result.author.username %}" class="block capitalize font-semibold dark:text-gray-100 irsa"> {{ result.author.get_full_name }} </a>
                                            <P class="px-3 py-2 irsa bg-white  rounded-lg"> قیمت {{ result.price }} تومان</P>
                                        </div>
                                        <div>
                                            <a> <i class="icon-feather-more-horizontal text-2xl hover:bg-gray-200 rounded-full p-2 transition -mr-1 dark:hover:bg-gray-700"></i> </a>
                                            <div class="bg-white w-56 shadow-1 mx-auto p-2 mt-12 rounded-md text-gray-500 hidden text-base border border-gray-100 dark:bg-gray-900 dark:text-gray-100 dark:border-gray-700" uk-drop="mode: hover;pos: top-right">

                                                <ul class="rtl space-y-1">
                                                    <li>
                                                        <button href="#" onclick="shareLinkP('{{ result.pk }}')" class="shareLink irsa flex items-center px-3 py-2 hover:bg-gray-200 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                                            <i class="uil-share-alt mr-1"></i> اشتراک گذاری
                                                        </button>
                                                    </li>
                                                    {% if result.author == request.user %}
                                                    <li>
                                                        <hr class="-mx-2 my-2 dark:border-gray-800">
                                                    </li>
                                                    <li>
                                                        <form action="" method="POST" class="irsa flex items-center px-3 py-2 text-red-500 hover:bg-red-100 hover:text-red-500 rounded-md dark:hover:bg-red-600">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="flag" value="{{ result.pk }}" />

                                                            <button type="submit" class="  irsa " /><i class="uil-trash-alt mr-1  mr-1 "></i> حذف<button>
                                                        </form>
                                                    </li>
                                                    {% endif %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="#" class="grid grid-cols-2 gap-3 lg:p-6 p-4">
                                        <h2 class="irsa text-2xl">{{ result.title }}</h2>
                                        <br>
                                        <p class="irsa">{{ result.body }}</p>
                                        <br>
                                        <!-- <p class="irsa px-2">{% jalali result.createdAdd as dateResult %}{{ dateResult.0 }}/{{ dateResult.1 }}/{{ dateResult.2 }}</p> -->
                                    </a>
                                    {% if result.author != request.user and request.user.ServiceProvider and validation_user %}
                                <a href="{% url "account:addAcceptRequest" result.pk  %}" class="py-2 px-3 rounded-2xl text-white irsa bg-treaget">قبول درخواست</a>
                                {% endif %}
                                </div>
                                {% for resultAccept in result.subcategories.all %}
                                <div  class="bg-white rounded-md shadow-1   rtl">
                                     <div class="flex justify-between items-center px-4 py-3 mt-3 rounded-lg bg-gray-100">
                                        <div class="flex flex-1 items-center space-x-4">
                                            <a href="{% url 'main:profile' resultAccept.author.username %}">
                                                <div class="mx-3    w-8 h-8 overflow-hidden "  style="border-radius:10px;">
                                                    <img src="{% if resultAccept.author.image %}{{ resultAccept.author.image.url }}{% else %}{% static 'inside/avatar.jpg' %}{% endif %}" class="">
                                                </div>
                                             </a>
                                        <a href="{% url 'main:profile' resultAccept.author.username %}" class="block capitalize font-semibold dark:text-gray-100 irsa"> {{ resultAccept.author.get_full_name }} </a>
                                        </div>

                                    </div>
                                    <div class="   lg:p-6 p-4">
                                        <p class="irsa text-dark text-2xl">{{ resultAccept.time }}</p>

                                        <!-- <p class="irsa  px-2">{% jalali resultAccept.createdAdd as dateResult %}{{ dateResult.0 }}/{{ dateResult.1 }}/{{ dateResult.2 }}</p> -->
                                    </div>
                                {% if result.author == request.user %}
                                <a href="{% url "account:createSafePayment" result.pk resultAccept.pk %}" class="py-3 px-3 rounded-lg text-white irsa bg-blue-600">ایجاد پرداخت امن</a>
                                {% endif %}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- post 2-->

                        <!-- Load more-->


                    </div>

                    <!-- right sidebar-->

                </div>


            </div>

        </div>

    </div>









 <!-- Scripts
    ================================================== -->
{% include "include/footer.html" %}

     <script>
    $('body').on('click', '.hapus_krs',function(){

        var formData = {
        'id_mhs': $(this).attr('value'),
        csrfmiddlewaretoken: '{{ csrf_token }}'
        };
        $.ajax({
            type: 'POST',
            url: `/account/LikePost/`,
            data: formData,
            dataType: 'json',
            encode: true
        })
        svgChannged = document.getElementById($(this).attr('value'));
        if (svgChannged.getAttribute("fill") == "blue") {
            svgChannged.setAttribute("fill", "");
        } else {
            svgChannged.setAttribute("fill", "blue");
        }

    });
    function shareLinkP(dataValue){
        let input = document.body.appendChild(document.createElement("input"));
        input.value = `${window.location.hostname}/request/${dataValue}`;
        input.focus();
        input.select();
        document.execCommand('copy');
        input.parentNode.removeChild(input);
        alert(`${window.location.hostname}/request/${dataValue} کپی شد.`)
    }
</script>
<script> (function($) {
      $('#lazyLoadLink').on('click', function() {
        var link = $(this);
        var page = link.data('page');
        $.ajax({
          type: 'post',
          url: 'lazy_load_posts/',
          data: {
            'page': page,
            'csrfmiddlewaretoken': window.CSRF_TOKEN // from index.html
          },
          success: function(data) {
            // if there are still more pages to load,
            // add 1 to the "Load More Posts" link's page data attribute
            // else hide the link
            if (data.has_next) {
                link.data('page', page+1);
            } else {
              link.hide();
            }
            // append html to the posts div
            console.log(data.posts_html)
            $('#posts').append(data.posts_html);
          },
          error: function(xhr, status, error) {
            // shit happens friends!
          }
        });
      });
    }(jQuery));</script>
</body>


</html>