account/urls.py
# The views used below are normally mapped in django.contrib.admin.urls.py
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path, include
from . import views as Function

app_name = "account"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('', Function.home, name='home'),
    path('picture/', Function.picture, name='picture'),
    path('post/<int:pk>/', Function.post, name='post'),
    path('lazy_load_posts/', Function.lazy_load_posts, name='lazy_load_posts'),
    path('logout/', Function.logout_view, name='logout'),
    path('addpicture/', Function.addPicture, name='addPicture'),
    path('addcv/', Function.addCv, name='addCv'),
    path('addsafepayment/<str:username>/',
         Function.addSafePayment, name='addSafePayment'),
    path('addSafePaymentOrder/<int:pk>/',
         Function.addSafePaymentOrder, name='addSafePaymentOrder'),
    path('deletecv/<int:pk>/', Function.deleteCv, name='deleteCv'),
    path('deleteservice/<int:pk>/', Function.deleteService, name='deleteService'),
    path('setting/', Function.profile, name='setting'),
    path('message/', Function.message, name='message'),
    path('message/<str:username>/', Function.message, name='messageUser'),
    path('register/', Function.register, name='register'),
    # path('OrderViews/', Function.OrderViews, name='OrderViews'),
    path('operate/', include('accounting.urls'), name="accounting"),
    path('addService/', Function.addService, name='addService'),
    path('LikePost/', Function.LikePost, name='LikePost'),
    path('follow/', Function.follow, name='follow'),
    path('follow/<str:username>/', Function.follow, name='follow_User'),
    path('p/<str:slug>/checkout/', Function.checkoutUser, name="checkoutUser"),
    path('p/<str:slug>/checkout/<int:service>/',
         Function.checkoutUser, name="checkoutUserService"),
    path('desk/', Function.desk, name="desk"),
    path('notification/', Function.notification, name="notification"),
    path('orders/', Function.orders, name="orders"),
    path('ordersTrue/<int:pk>/', Function.ordersTrue, name="ordersTrue"),
    path('ordersFalse/<int:pk>/', Function.ordersFalse, name="ordersFalse"),
    path('listSafePayment/', Function.listSafePayment, name="listSafePayment"),
    path('listDispute/', Function.listDispute, name="listDispute"),
    path('addDispute/<int:pk>/', Function.addDispute, name="addDispute"),
    path('SafePaymentRefuse/<int:pk>/',
         Function.SafePaymentRefuse, name="SafePaymentRefuse"),
    path('SafePaymentAccept/<int:pk>/',
         Function.SafePaymentAccept, name="SafePaymentAccept"),
    path('createSafePayment/<int:pk_request>/<int:pk_accept>/',
         Function.createSafePayment, name="createSafePayment"),
    path('addRequest/', Function.addRequest, name="addRequest"),
    path('addAcceptRequest/<int:pk>/',
         Function.addAcceptRequest, name="addAcceptRequest"),
    path('projectManagement/<int:pk>/',
         Function.projectManagement, name="projectManagement"),
    path('DeleteProjectManagement/<int:pk>/',
         Function.deleteSubsetTrello, name="deleteSubsetTrello"),
    path('DeleteProjectManagementMain/<int:pk>/',
         Function.deleteTrello, name="deleteTrello"),
    path('AddSubsetProjectManagement/<int:pk>/',
         Function.AddSubsetProjectManagement, name="AddSubsetProjectManagement"),
    path('AddProjectManagement/<int:pk>/',
         Function.AddProjectManagement, name="AddProjectManagement"),
    path('numberOfFollowers/<str:username>/',
         Function.numberOfFollowers, name="numberOfFollowers"),
    path('numberOfFollowing/<str:username>/',
         Function.numberOfFollowing, name="numberOfFollowing"),

    # path('change_picture/<int:pk>', change_picture, name='change-picture'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),


]

api/urls.py
from django.urls import  include, path,re_path
from . import views
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth import views as auth_view


router = routers.SimpleRouter()
router.register(r'HomeApiView', views.HomeApiView, basename="HomeApiView")


urlpatterns = [
# urls.py
     path('social/google/', include("social_django.urls", namespace='social')),
     path('blog/', include('blog.urls')),
     path('login/', auth_view.LoginView.as_view(), name='login'),
     path('token/', obtain_auth_token),
     path('CheckToken/', views.CheckToken.as_view(), name="CheckToken"),
     # path('token/', TokenObtainPairView.as_view(),name='token_obtain_pair'),
     # path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
     path('ExploreApiView/', views.ExploreApiView.as_view(), name="ExploreApiView"),
     path('ExploreProjectApiView/', views.ExploreProjectApiView.as_view(),
          name="ExploreProjectApiView"),
     path('AddLikeView/', views.AddLikeView.as_view(), name="AddLikeView"),
     path('MassageApi/', views.MassageApi.as_view(), name="MassageApi"),
     path('AllMassageApi/', views.AllMassageApi.as_view(), name="AllMassageApi"),
     path('FollowUnfollowApi/<str:username>/',
          views.FollowUnfollowApi.as_view(), name="FollowUnfollowApi"),



     # get data like this ?&min_price=50001&max_price=80000&search=logo&ordering=-price


     path('PicturePostDestroyRetrive/<int:pk>/',
          views.PicturePostDestroyRetrive.as_view(), name="PicturePostDestroyRetrive"),
     path('RequestPostDestroyRetrive/<int:pk>/',
          views.RequestPostDestroyRetrive.as_view(), name="RequestPostDestroyRetrive"),
     path('AddAcceptRequestApi/<int:pk>/',
          views.AddAcceptRequestApi.as_view(), name="AddAcceptRequestApi"),
     path('AddRequestApi/', views.AddRequestApi.as_view(), name="AddRequestApi"),
     path('RequestListApi/<str:username>/', views.RequestListApi.as_view(), name="RequestListApi"),
     path('DestroyRequestApi/<int:pk>/', views.DestroyRequestApi.as_view(), name="DestroyRequestApi"),
     path('RequestSearchApi/', views.RequestSearchApi.as_view(),name="RequestSearchApi"),
     path('PictureSearchApi/', views.PictureSearchApi.as_view(),
          name="PictureSearchApi"),
     path('UserSettingApi/',
          views.UserSettingApi.as_view(), name="UserSettingApi"),
     path('UserRetrieveApi/<str:username>/',
          views.UserRetrieveApi.as_view(), name="UserRetrieveApi"),
     path('UserSearchListApi/', views.UserSearchListApi.as_view(),
          name="UserSearchListApi"),
     path('AddPostPictureApi/', views.AddPostPictureApi.as_view(),
          name="AddPostPictureApi"),
     path('UserCreate/', views.UserCreate.as_view(), name="UserCreate"),
     path('NotificationApi/', views.NotificationApi.as_view(), name="NotificationApi"),
     path('CashApi/', views.CashApi.as_view(), name="CashApi"),
     path('PaymentWalletApi/', views.PaymentWalletApi.as_view(),
          name="PaymentWalletApi"),
     path('favoritesApi/<str:username>/',
          views.favoritesApi.as_view(), name="favoritesApi"),
     path('SafePaymentApi/', views.SafePaymentApi.as_view(), name="SafePaymentApi"),
     path('TrelloApi/<int:pk>/', views.TrelloApi.as_view(), name="TrelloApi"),
     path('SubsetTrelloDestroyApi/<int:pk>/',
          views.SubsetTrelloDestroyApi.as_view(), name="SubsetTrelloDestroyApi"),
     path('DisputeApi/', views.DisputeApi.as_view(), name="DisputeApi"),
     path('DisputeDestroyApi/<int:pk>/',
          views.DisputeDestroyApi.as_view(), name="DisputeDestroyApi"),
     path('AddDisputeApi/',
          views.AddDisputeApi.as_view(), name="AddDisputeApi"),
     path('OrderApi/', views.OrderApi.as_view(), name="OrderApi"),
     path('AddOrderApi/<str:username>/', views.AddOrderApi.as_view(), name="AddOrderApi"),
     path('OrderTrueApi/',
          views.OrderTrueApi.as_view(), name="OrderTrueApi"),
     path('OrderFalseApi/',
          views.OrderFalseApi.as_view(), name="OrderFalseApi"),
     path('CountReadStatus/', views.CountReadStatus.as_view(), name="CountReadStatus"),
     path('PicturePostListApi/<str:username>/',
          views.PicturePostListApi.as_view(), name="PicturePostListApi"),
     path('ListUserMessageApi/', views.ListUserMessageApi.as_view(),
          name="ListUserMessageApi"),
     path('DeskApi/', views.DeskApi.as_view(),name="DeskApi"),
     path('AcceptSafePaymentApi/', views.AcceptSafePaymentApi.as_view(),name="AcceptSafePaymentApi"),
     path('RefuseSafePaymentApi/', views.RefuseSafePaymentApi.as_view(),name="RefuseSafePaymentApi"),
     path('RulesListApi/', views.RulesListApi.as_view(),name="RulesListApi"),
     path('SpamCreateApi/', views.SpamCreateApi.as_view(),name="SpamCreateApi"),
     path('UserSuggestion/', views.User_suggestion.as_view(),name="User_suggestion"),
     path('Send_code/', views.Send_code.as_view(),name="Send_code"),
     path('Code_check/', views.Code_check.as_view(),name="Code_check"),
     path('PostTagApi/', views.PostTagApi.as_view(),name="PostTagApi"),
     path('following/', views.following.as_view(),name="following"),
     path('followingList/', views.followingList.as_view(),name="followingList"),
     path('followersList/', views.followersList.as_view(),name="followersList"),
     path('ContactApi/', views.ContactApi.as_view(),name="ContactApi"),
]

urlpatterns += router.urls

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from . import views
from account.views import cv, service, favourites

app_name="main"
urlpatterns = [
    path('', views.index,name="main"),
    path('explore/', views.explore,name="explore"),
    path('explore/lazy_load_posts/', views.lazyLoadExplore,name="lazy_load_posts"),
    path('contact/', views.Contact,name="contact"),
    path('p/<str:slug>/', views.profile , name="profile"),
    path('p/<str:slug>/cv', cv, name="cv"),
    path('p/<str:slug>/service', service , name="service"),
    path('p/<str:slug>/favourites', favourites, name="favourites"),
    path('search/', views.search , name="search"),
    path('Rules/', views.rules, name="Rules"),
    path('request/<int:pk>/', views.requestUser, name="request"),

]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


wallet/urls.py
from django.urls import path, include
from . import views
app_name="wallet"
urlpatterns = [
    path('', views.wallet, name="wallet"),
    path('IncreaseMoney/', views.increaseMoney, name="increaseMoney"),
    path('IncreaseMoney/<int:amount>/', views.increaseMoney, name="increaseMoneyAmount"),
    path('WithdrawMoney/', views.withdrawMoney, name="WithdrawMoney"),
    path('verify/<int:amount>/', views.verify, name="verify"),
    path('enamad/', views.enamad, name="verify"),
    path('wWithdrawMoneyApi/', views.wWithdrawMoneyApi.as_view(), name="wWithdrawMoneyApi"),
    path('listTransaction/', views.listTransaction.as_view(), name="listTransaction"),
    
]

templates/include/sidebar.html
 {% load static %}
<div class="sidebar shadow-sidebar bg-white" id="sidebar">
    <div class="sidebar_header   uk-visible@s">
        <a href="#">
            <img src="{% static 'main/img/treaget-img.png' %}" style="width: 62px">

        </a>
        <!-- btn night mode -->
        <div class="irsa text-black" style="margin-left:15px;font-size:25px;">treaget</div>
    </div>
    <div class="flex justify-between items-center p-2 pl-5 relative uk-hidden@s">
        <h3 class="text-xl">treaget</h3>
        <span class="" uk-toggle="target: #wrapper ; cls: sidebar-active"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                </svg></span>
    </div>
    <div class="sidebar_inner " data-simplebar>
        <div class="flex flex-col items-center my-6 ">
            <div class="   w-24 h-24 overflow-hidden shadow-1" style="border-radius:39px;">
                <img src="{% if request.user.image %}{{ request.user.image.url }}{% else %}{% static 'inside/avatar.jpg' %}{% endif %}" class=" w-full  overflow-hidden">
            </div>
            <div class="text-xl  capitalize mt-4 uk-link-reset irsa"> {{request.user.get_full_name}}
            </div>
            <div class="flex justify-around w-full items-center text-center uk-link-reset text-gray-800 mt-6">
                <div>
                    <div href="#">
                        <p class="irsa text-muted">بازدید</p>
                        <div>
                            {% if request.user.numberVisitors.count %}{{ request.user.numberVisitors.count }}{% else %}0{% endif %}
                        </div>
                    </div>
                </div>

                <div>
                    <a href="{% if request.user.username %}{% url 'account:numberOfFollowers' request.user.username %}{% endif %}">
                        <p class="irsa text-muted">دنبال کننده</p>
                        <div>
                            {% if request.user.followers.count %}{{ request.user.followers.count }}{% else %}0{% endif %}
                        </div>
                    </a>
                </div>
                <div>
                    <a href="{% if request.user.username %}{% url 'account:numberOfFollowing' request.user.username %}{% endif %}">
                        <p class="irsa text-muted">دنبال شونده</p>
                        <div>
                            {% if request.user.following.count %}{{ request.user.following.count }}{% else %}0{% endif %}
                        </div>
                    </a>
                </div>

            </div>
        </div>
        <!-- <hr class="-mx-4  -mt-1 uk-visible@s"> -->
        <ul class="text-right ">
            <div>
                <li>
                    <span class="irsa mr-4" style="color:#E0E0E0"> منو </span>
                </li>
                <li>
                    <a href="{% url 'account:home' %}" class="rtl hover:text-yellow rounded-2xl {% if request.resolver_match.url_name == 'home' %} active_navbar {% else %} navbar_menu {% endif %}">
                        <div class="child_menu"></div><svg xmlns="http://www.w3.org/2000/svg" style="transform: scale(.8);" fill="currentColor" id="Outline" viewBox="0 0 24 24"><path d="M23.121,9.069,15.536,1.483a5.008,5.008,0,0,0-7.072,0L.879,9.069A2.978,2.978,0,0,0,0,11.19v9.817a3,3,0,0,0,3,3H21a3,3,0,0,0,3-3V11.19A2.978,2.978,0,0,0,23.121,9.069ZM15,22.007H9V18.073a3,3,0,0,1,6,0Zm7-1a1,1,0,0,1-1,1H17V18.073a5,5,0,0,0-10,0v3.934H3a1,1,0,0,1-1-1V11.19a1.008,1.008,0,0,1,.293-.707L9.878,2.9a3.008,3.008,0,0,1,4.244,0l7.585,7.586A1.008,1.008,0,0,1,22,11.19Z"/></svg>
                        <span class="irsa mr-4 "> خانه </span> </a>
                </li>
                <li>
                    <a href="{% url 'main:explore' %}" class="rtl hover:text-yellow {% if request.resolver_match.url_name == 'explore' %} active_navbar  {% else %} navbar_menu {% endif %}">
                        <div class="child_menu"></div><svg xmlns="http://www.w3.org/2000/svg" style="transform: scale(.8);" fill="currentColor" id="Outline" viewBox="0 0 24 24"><path d="M23.707,22.293l-5.969-5.969a10.016,10.016,0,1,0-1.414,1.414l5.969,5.969a1,1,0,0,0,1.414-1.414ZM10,18a8,8,0,1,1,8-8A8.009,8.009,0,0,1,10,18Z"/></svg>
                        <span class="irsa mr-4"> کاوش </span> </a>
                </li>
                <li>
                    <a href="{% url 'account:message' %}" class="rtl hover:text-yellow {% if request.resolver_match.url_name == 'message' %} active_navbar  {% else %} navbar_menu {% endif %}">
                        <div class="child_menu"></div><svg xmlns="http://www.w3.org/2000/svg" style="transform: scale(.8);" fill="currentColor" id="Outline" viewBox="0 0 24 24"><path d="M24,11.247A12.012,12.012,0,1,0,12.017,24H19a5.005,5.005,0,0,0,5-5V11.247ZM22,19a3,3,0,0,1-3,3H12.017a10.041,10.041,0,0,1-7.476-3.343,9.917,9.917,0,0,1-2.476-7.814,10.043,10.043,0,0,1,8.656-8.761A10.564,10.564,0,0,1,12.021,2,9.921,9.921,0,0,1,18.4,4.3,10.041,10.041,0,0,1,22,11.342Z"/><path d="M8,9h4a1,1,0,0,0,0-2H8A1,1,0,0,0,8,9Z"/><path d="M16,11H8a1,1,0,0,0,0,2h8a1,1,0,0,0,0-2Z"/><path d="M16,15H8a1,1,0,0,0,0,2h8a1,1,0,0,0,0-2Z"/></svg>
                        <span class="irsa mr-4"> گپ </span> <span class="nav-tag bg-treaget mx-1" v-if="counterMessage">[[ counterMessage ]]</span></a>
                    <li>
                        <a href="{% url 'account:desk' %}" class="rtl d-flex hover:text-yellow {% if request.resolver_match.url_name == 'desk' %} active_navbar  {% else %} navbar_menu {% endif %}">
                            <div class="child_menu"></div><svg xmlns="http://www.w3.org/2000/svg" style="transform: scale(.8);" id="Outline" fill="currentColor" viewBox="0 0 24 24">
                           <path d="M7,0H4A4,4,0,0,0,0,4V7a4,4,0,0,0,4,4H7a4,4,0,0,0,4-4V4A4,4,0,0,0,7,0ZM9,7A2,2,0,0,1,7,9H4A2,2,0,0,1,2,7V4A2,2,0,0,1,4,2H7A2,2,0,0,1,9,4Z"/><path d="M20,0H17a4,4,0,0,0-4,4V7a4,4,0,0,0,4,4h3a4,4,0,0,0,4-4V4A4,4,0,0,0,20,0Zm2,7a2,2,0,0,1-2,2H17a2,2,0,0,1-2-2V4a2,2,0,0,1,2-2h3a2,2,0,0,1,2,2Z"/><path d="M7,13H4a4,4,0,0,0-4,4v3a4,4,0,0,0,4,4H7a4,4,0,0,0,4-4V17A4,4,0,0,0,7,13Zm2,7a2,2,0,0,1-2,2H4a2,2,0,0,1-2-2V17a2,2,0,0,1,2-2H7a2,2,0,0,1,2,2Z"/><path d="M20,13H17a4,4,0,0,0-4,4v3a4,4,0,0,0,4,4h3a4,4,0,0,0,4-4V17A4,4,0,0,0,20,13Zm2,7a2,2,0,0,1-2,2H17a2,2,0,0,1-2-2V17a2,2,0,0,1,2-2h3a2,2,0,0,1,2,2Z"/></svg>
                            <span class="irsa mr-4">میزکار</span><span class="nav-tag bg-treaget mx-1" v-if="counterNotification">[[ counterNotification ]]</span> </a>


                    </li>
                    <li>
                        <a href="{% if request.user.username %}{% url 'main:profile' request.user.username %}{% endif %}" class="rtl hover:text-yellow {% if request.resolver_match.url_name == 'profile' %} active_navbar {% else %} navbar_menu {% endif %}">
                            <div class="child_menu"></div><svg xmlns="http://www.w3.org/2000/svg" style="transform: scale(.8);" fill="currentColor" id="Outline" viewBox="0 0 24 24"><path d="M12,12A6,6,0,1,0,6,6,6.006,6.006,0,0,0,12,12ZM12,2A4,4,0,1,1,8,6,4,4,0,0,1,12,2Z"/><path d="M12,14a9.01,9.01,0,0,0-9,9,1,1,0,0,0,2,0,7,7,0,0,1,14,0,1,1,0,0,0,2,0A9.01,9.01,0,0,0,12,14Z"/></svg>
                            <span class="irsa mr-4"> صفحه ی من </span>

                        </a>
                    </li>
            </div>
            <li>
                <span class="irsa mr-4" style="color:#E0E0E0"> عمومی </span>
            </li>
            <li>
                <a href="{% url 'account:setting' %}" class="rtl hover:text-yellow {% if request.resolver_match.url_name == 'setting' %} active_navbar  {% else %} navbar_menu {% endif %}">
                    <svg xmlns="http://www.w3.org/2000/svg" style="transform: scale(.8);" fill="currentColor" id="Outline" viewBox="0 0 24 24"><path d="M12,8a4,4,0,1,0,4,4A4,4,0,0,0,12,8Zm0,6a2,2,0,1,1,2-2A2,2,0,0,1,12,14Z"/><path d="M21.294,13.9l-.444-.256a9.1,9.1,0,0,0,0-3.29l.444-.256a3,3,0,1,0-3-5.2l-.445.257A8.977,8.977,0,0,0,15,3.513V3A3,3,0,0,0,9,3v.513A8.977,8.977,0,0,0,6.152,5.159L5.705,4.9a3,3,0,0,0-3,5.2l.444.256a9.1,9.1,0,0,0,0,3.29l-.444.256a3,3,0,1,0,3,5.2l.445-.257A8.977,8.977,0,0,0,9,20.487V21a3,3,0,0,0,6,0v-.513a8.977,8.977,0,0,0,2.848-1.646l.447.258a3,3,0,0,0,3-5.2Zm-2.548-3.776a7.048,7.048,0,0,1,0,3.75,1,1,0,0,0,.464,1.133l1.084.626a1,1,0,0,1-1,1.733l-1.086-.628a1,1,0,0,0-1.215.165,6.984,6.984,0,0,1-3.243,1.875,1,1,0,0,0-.751.969V21a1,1,0,0,1-2,0V19.748a1,1,0,0,0-.751-.969A6.984,6.984,0,0,1,7.006,16.9a1,1,0,0,0-1.215-.165l-1.084.627a1,1,0,1,1-1-1.732l1.084-.626a1,1,0,0,0,.464-1.133,7.048,7.048,0,0,1,0-3.75A1,1,0,0,0,4.79,8.992L3.706,8.366a1,1,0,0,1,1-1.733l1.086.628A1,1,0,0,0,7.006,7.1a6.984,6.984,0,0,1,3.243-1.875A1,1,0,0,0,11,4.252V3a1,1,0,0,1,2,0V4.252a1,1,0,0,0,.751.969A6.984,6.984,0,0,1,16.994,7.1a1,1,0,0,0,1.215.165l1.084-.627a1,1,0,1,1,1,1.732l-1.084.626A1,1,0,0,0,18.746,10.125Z"/></svg>
                    <span class="irsa mr-4">تنظیمات</span> </a>
            </li>


            <li>
                <a href="{% url 'account:logout' %}" class="rtl hover:text-yellow navbar_menu">
                    <svg xmlns="http://www.w3.org/2000/svg" width="4" height="4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                            </svg>
                    <span class="irsa mr-4"> خروج </span> </a>

            </li>
            {% comment %}
            <li class="mb-1 rounded-2xl bg-treaget shadow-1 py-1 w-full h-full mt-5" style="background-image: url(../static/main/img/software/bg-soft.png);   
            ">
                <div class="text-white">کیف پول</div>
                <div class="d-flex justify-content-center">00000.00</div>
                <div class="d-flex">
                    <div class="bg-glass-dark m-2 border-t text-white shadow-1 px-3 py-1 text-xs rounded-lg">تراکنش ها</div>
                    <div class="bg-glass-dark border-t m-2 shadow-1 text-white px-3 py-1  text-xs rounded-lg">واریز پول</div>
                </div>
            </li>
            {% endcomment %}
            <a class="uk-button uk-button-default invisible" id="numberCheck" href="#modal-full" uk-toggle></a>

            <div id="modal-full" class="uk-modal-full bg-glass" uk-modal>
                <div class="uk-modal-dialog ">
                    <button class="uk-modal-close-full uk-close-large invisible" id="closeSms" type="button" uk-close></button>
                    <div class=" pt-5 center">
                        <div class=" container rtl col-9   pt-5 " uk-height-viewport>
                            <h1>کد دریافتی به شماره تلفن خود را وارد کنید</h1>
                            <div class="py-3 px-5 text-danger" v-if="statusCheck == true">خطایی رخ داد ممکن است کد را اشتباه وارد کرده باشید</div>
                            <input type="text" pattern="[0-9.]+" maxlength="5" minlength="5" v-model="code" class="shadow-none bg-gray-100 border mt-5">
                            <div> <button class="px-5 rounded-full  py-2 bg-treaget text-white mt-5" @click="sendNumber()" type="button">ثبت</button>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </ul>
    </div>
</div>