account/urls.py
# The views used below are normally mapped in django.contrib.admin.urls.py
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path, include
from . import views as Function

app_name = "account"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('', Function.home, name='home'),
    path('picture/', Function.picture, name='picture'),
    path('post/<int:pk>/', Function.post, name='post'),
    path('lazy_load_posts/', Function.lazy_load_posts, name='lazy_load_posts'),
    path('logout/', Function.logout_view, name='logout'),
    path('addpicture/', Function.addPicture, name='addPicture'),
    path('addcv/', Function.addCv, name='addCv'),
    path('addsafepayment/<str:username>/',
         Function.addSafePayment, name='addSafePayment'),
    path('addSafePaymentOrder/<int:pk>/',
         Function.addSafePaymentOrder, name='addSafePaymentOrder'),
    path('deletecv/<int:pk>/', Function.deleteCv, name='deleteCv'),
    path('deleteservice/<int:pk>/', Function.deleteService, name='deleteService'),
    path('setting/', Function.profile, name='setting'),
    path('message/', Function.message, name='message'),
    path('message/<str:username>/', Function.message, name='messageUser'),
    path('register/', Function.register, name='register'),
    # path('OrderViews/', Function.OrderViews, name='OrderViews'),
    path('operate/', include('accounting.urls'), name="accounting"),
    path('addService/', Function.addService, name='addService'),
    path('LikePost/', Function.LikePost, name='LikePost'),
    path('follow/', Function.follow, name='follow'),
    path('follow/<str:username>/', Function.follow, name='follow_User'),
    path('p/<str:slug>/checkout/', Function.checkoutUser, name="checkoutUser"),
    path('p/<str:slug>/checkout/<int:service>/',
         Function.checkoutUser, name="checkoutUserService"),
    path('desk/', Function.desk, name="desk"),
    path('notification/', Function.notification, name="notification"),
    path('orders/', Function.orders, name="orders"),
    path('ordersTrue/<int:pk>/', Function.ordersTrue, name="ordersTrue"),
    path('ordersFalse/<int:pk>/', Function.ordersFalse, name="ordersFalse"),
    path('listSafePayment/', Function.listSafePayment, name="listSafePayment"),
    path('listDispute/', Function.listDispute, name="listDispute"),
    path('addDispute/<int:pk>/', Function.addDispute, name="addDispute"),
    path('SafePaymentRefuse/<int:pk>/',
         Function.SafePaymentRefuse, name="SafePaymentRefuse"),
    path('SafePaymentAccept/<int:pk>/',
         Function.SafePaymentAccept, name="SafePaymentAccept"),
    path('createSafePayment/<int:pk_request>/<int:pk_accept>/',
         Function.createSafePayment, name="createSafePayment"),
    path('addRequest/', Function.addRequest, name="addRequest"),
    path('addAcceptRequest/<int:pk>/',
         Function.addAcceptRequest, name="addAcceptRequest"),
    path('projectManagement/<int:pk>/',
         Function.projectManagement, name="projectManagement"),
    path('DeleteProjectManagement/<int:pk>/',
         Function.deleteSubsetTrello, name="deleteSubsetTrello"),
    path('DeleteProjectManagementMain/<int:pk>/',
         Function.deleteTrello, name="deleteTrello"),
    path('AddSubsetProjectManagement/<int:pk>/',
         Function.AddSubsetProjectManagement, name="AddSubsetProjectManagement"),
    path('AddProjectManagement/<int:pk>/',
         Function.AddProjectManagement, name="AddProjectManagement"),
    path('numberOfFollowers/<str:username>/',
         Function.numberOfFollowers, name="numberOfFollowers"),
    path('numberOfFollowing/<str:username>/',
         Function.numberOfFollowing, name="numberOfFollowing"),

    # path('change_picture/<int:pk>', change_picture, name='change-picture'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),


]

api/urls.py
from django.urls import  include, path,re_path
from . import views
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth import views as auth_view


router = routers.SimpleRouter()
router.register(r'HomeApiView', views.HomeApiView, basename="HomeApiView")


urlpatterns = [
# urls.py
     path('social/google/', include("social_django.urls", namespace='social')),
     path('blog/', include('blog.urls')),
     path('login/', auth_view.LoginView.as_view(), name='login'),
     path('token/', obtain_auth_token),
     path('CheckToken/', views.CheckToken.as_view(), name="CheckToken"),
     # path('token/', TokenObtainPairView.as_view(),name='token_obtain_pair'),
     # path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
     path('ExploreApiView/', views.ExploreApiView.as_view(), name="ExploreApiView"),
     path('ExploreProjectApiView/', views.ExploreProjectApiView.as_view(),
          name="ExploreProjectApiView"),
     path('AddLikeView/', views.AddLikeView.as_view(), name="AddLikeView"),
     path('MassageApi/', views.MassageApi.as_view(), name="MassageApi"),
     path('AllMassageApi/', views.AllMassageApi.as_view(), name="AllMassageApi"),
     path('FollowUnfollowApi/<str:username>/',
          views.FollowUnfollowApi.as_view(), name="FollowUnfollowApi"),



     # get data like this ?&min_price=50001&max_price=80000&search=logo&ordering=-price


     path('PicturePostDestroyRetrive/<int:pk>/',
          views.PicturePostDestroyRetrive.as_view(), name="PicturePostDestroyRetrive"),
     path('RequestPostDestroyRetrive/<int:pk>/',
          views.RequestPostDestroyRetrive.as_view(), name="RequestPostDestroyRetrive"),
     path('AddAcceptRequestApi/<int:pk>/',
          views.AddAcceptRequestApi.as_view(), name="AddAcceptRequestApi"),
     path('AddRequestApi/', views.AddRequestApi.as_view(), name="AddRequestApi"),
     path('RequestListApi/<str:username>/', views.RequestListApi.as_view(), name="RequestListApi"),
     path('DestroyRequestApi/<int:pk>/', views.DestroyRequestApi.as_view(), name="DestroyRequestApi"),
     path('RequestSearchApi/', views.RequestSearchApi.as_view(),name="RequestSearchApi"),
     path('PictureSearchApi/', views.PictureSearchApi.as_view(),
          name="PictureSearchApi"),
     path('UserSettingApi/',
          views.UserSettingApi.as_view(), name="UserSettingApi"),
     path('UserRetrieveApi/<str:username>/',
          views.UserRetrieveApi.as_view(), name="UserRetrieveApi"),
     path('UserSearchListApi/', views.UserSearchListApi.as_view(),
          name="UserSearchListApi"),
     path('AddPostPictureApi/', views.AddPostPictureApi.as_view(),
          name="AddPostPictureApi"),
     path('UserCreate/', views.UserCreate.as_view(), name="UserCreate"),
     path('NotificationApi/', views.NotificationApi.as_view(), name="NotificationApi"),
     path('CashApi/', views.CashApi.as_view(), name="CashApi"),
     path('PaymentWalletApi/', views.PaymentWalletApi.as_view(),
          name="PaymentWalletApi"),
     path('favoritesApi/<str:username>/',
          views.favoritesApi.as_view(), name="favoritesApi"),
     path('SafePaymentApi/', views.SafePaymentApi.as_view(), name="SafePaymentApi"),
     path('TrelloApi/<int:pk>/', views.TrelloApi.as_view(), name="TrelloApi"),
     path('SubsetTrelloDestroyApi/<int:pk>/',
          views.SubsetTrelloDestroyApi.as_view(), name="SubsetTrelloDestroyApi"),
     path('DisputeApi/', views.DisputeApi.as_view(), name="DisputeApi"),
     path('DisputeDestroyApi/<int:pk>/',
          views.DisputeDestroyApi.as_view(), name="DisputeDestroyApi"),
     path('AddDisputeApi/',
          views.AddDisputeApi.as_view(), name="AddDisputeApi"),
     path('OrderApi/', views.OrderApi.as_view(), name="OrderApi"),
     path('AddOrderApi/<str:username>/', views.AddOrderApi.as_view(), name="AddOrderApi"),
     path('OrderTrueApi/',
          views.OrderTrueApi.as_view(), name="OrderTrueApi"),
     path('OrderFalseApi/',
          views.OrderFalseApi.as_view(), name="OrderFalseApi"),
     path('CountReadStatus/', views.CountReadStatus.as_view(), name="CountReadStatus"),
     path('PicturePostListApi/<str:username>/',
          views.PicturePostListApi.as_view(), name="PicturePostListApi"),
     path('ListUserMessageApi/', views.ListUserMessageApi.as_view(),
          name="ListUserMessageApi"),
     path('DeskApi/', views.DeskApi.as_view(),name="DeskApi"),
     path('AcceptSafePaymentApi/', views.AcceptSafePaymentApi.as_view(),name="AcceptSafePaymentApi"),
     path('RefuseSafePaymentApi/', views.RefuseSafePaymentApi.as_view(),name="RefuseSafePaymentApi"),
     path('RulesListApi/', views.RulesListApi.as_view(),name="RulesListApi"),
     path('SpamCreateApi/', views.SpamCreateApi.as_view(),name="SpamCreateApi"),
     path('UserSuggestion/', views.User_suggestion.as_view(),name="User_suggestion"),
     path('Send_code/', views.Send_code.as_view(),name="Send_code"),
     path('Code_check/', views.Code_check.as_view(),name="Code_check"),
     path('PostTagApi/', views.PostTagApi.as_view(),name="PostTagApi"),
     path('following/', views.following.as_view(),name="following"),
     path('followingList/', views.followingList.as_view(),name="followingList"),
     path('followersList/', views.followersList.as_view(),name="followersList"),
     path('ContactApi/', views.ContactApi.as_view(),name="ContactApi"),
]

urlpatterns += router.urls

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from . import views
from account.views import cv, service, favourites

app_name="main"
urlpatterns = [
    path('', views.index,name="main"),
    path('explore/', views.explore,name="explore"),
    path('explore/lazy_load_posts/', views.lazyLoadExplore,name="lazy_load_posts"),
    path('contact/', views.Contact,name="contact"),
    path('p/<str:slug>/', views.profile , name="profile"),
    path('p/<str:slug>/cv', cv, name="cv"),
    path('p/<str:slug>/service', service , name="service"),
    path('p/<str:slug>/favourites', favourites, name="favourites"),
    path('search/', views.search , name="search"),
    path('Rules/', views.rules, name="Rules"),
    path('request/<int:pk>/', views.requestUser, name="request"),

]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


wallet/urls.py
from django.urls import path, include
from . import views
app_name="wallet"
urlpatterns = [
    path('', views.wallet, name="wallet"),
    path('IncreaseMoney/', views.increaseMoney, name="increaseMoney"),
    path('IncreaseMoney/<int:amount>/', views.increaseMoney, name="increaseMoneyAmount"),
    path('WithdrawMoney/', views.withdrawMoney, name="WithdrawMoney"),
    path('verify/<int:amount>/', views.verify, name="verify"),
    path('enamad/', views.enamad, name="verify"),
    path('wWithdrawMoneyApi/', views.wWithdrawMoneyApi.as_view(), name="wWithdrawMoneyApi"),
    path('listTransaction/', views.listTransaction.as_view(), name="listTransaction"),
    
]

wallet/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from wallet.models import PaymentWalletB
from zeep import Client





from ast import Try
from unicodedata import category
from main.views import deleteDuplicate
from django.http import request
from rest_framework.authtoken.models import Token
from rest_framework.filters import OrderingFilter
from api.filterset_class import *
from extensions.notification import notificationAdd
from account.models import Message, Notification
import json
from django.utils.html import json_script
from rest_framework import status
from operator import attrgetter
from django.db.models.query_utils import Q
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.authentication import SessionAuthentication
from rest_framework import generics
from main.models import *
from .serializers import *
from rest_framework import viewsets
from django_filters import rest_framework as filterSpecial  
from rest_framework import filters
from api.pagination import MyPagination
import random
import requests

# Create your views here.
MERCHANT = 'd16f23cc-5cde-4cfb-bd0d-f5121b0887c8'
email = ''  # Optional
mobile = ''  # Optional
CallbackURL = 'http://treaget.com/api/wallet/verify/'  # Important: need to edit for realy server.
description = "شارژ کیف پول تریگت"  # Required


@login_required
def wallet(request):
    context = {

    }
    return render(request, 'desk/wallet.html', context)


@login_required
def withdrawMoney(request):
    if request.method == "POST":
        amount = request.POST.get("number")
        cardNumber = request.POST.get("cardNumber")
        name = request.POST.get("name")
        if int(amount) > request.user.cash:
            context = {
                'error': "مبلغ انتخابی بیشتر از مبلغ موجود در کیف پول شماست"
            }
            return render(request, 'desk/wallet.html', context)
        elif int(amount) == 0:
            context = {
                'error': "مبلغ انتخابی نباید صفر باشد"
            }
            return render(request, 'desk/wallet.html', context)
        elif int(amount) <= request.user.cash:
            PaymentWallet = PaymentWalletB(user=request.user, cash=amount, typePayment=False, cardNumber=cardNumber,
                                              name=name)
            context = {
                'success': "عملیات موفقیت آمیز بود . پرداخت حداکثر ظرف 48 ساعت دیگر انجام می شود"
            }
            return render(request, 'desk/wallet.html', context)
    return redirect('/wallet')




class wWithdrawMoneyApi(APIView):
    def post(self, request):
        data = json.loads(request.data)
        amount = data["number"]
        cardNumber = data['cardNumber']
        name = data['name']
        if int(amount) > request.user.cash:
            return Response(status=status.HTTP_406_NOT_ACCEPTABLE)
        elif int(amount) <= 0:
            return Response(status=status.HTTP_406_NOT_ACCEPTABLE)
        elif int(amount) <= request.user.cash:
            PaymentWallet = PaymentWalletB(user=request.user, cash=amount, typePayment=False, cardNumber=cardNumber,
                                            name=name)
            return Response(status=status.HTTP_200_OK)


class listTransaction(generics.ListAPIView):
    serializer_class = PaymentWalletSerializer
    def get_queryset(self):
        return PaymentWalletB.objects.filter(user=self.request.user)


@login_required
def increaseMoney(request, amount=None):
    client = Client('https://www.zarinpal.com/pg/services/WebGate/wsdl')

    if amount is None:
        amount = request.POST.get("number")
    result = client.service.PaymentRequest(MERCHANT, int(amount), description, email, mobile,
                                           CallbackURL + str(amount))
    if result.Status == 100:
        return redirect('https://www.zarinpal.com/pg/StartPay/' + str(result.Authority))
    else:
        return HttpResponse(
            'خطایی در انجام تراکنش مشاهده شد لطفا مدتی دیگر مجدد امتحان کنید \n Error code: ' + str(result.Status))


def verify(request, amount):
    client = Client('https://www.zarinpal.com/pg/services/WebGate/wsdl')
    if request.GET.get('Status') == 'OK':
        result = client.service.PaymentVerification(MERCHANT, request.GET['Authority'], amount)
        if result.Status == 100:
            UserPay = request.user
            UserPay.cash = UserPay.cash + int(amount)
            paymentResult = PaymentWalletB.objects.create(user=request.user, cash=amount, RefID=str(result.RefID))
            paymentResult.save()
            return redirect("/wallet/")
        elif result.Status == 101:
            return HttpResponse('Transaction submitted : ' + str(result.Status))
        else:
            return HttpResponse('Transaction failed.\nStatus: ' + str(result.Status))
    else:
        return HttpResponse('Transaction failed or canceled by user')



def enamad(request):
    return render(request, 'main/enamad.html')

templates/desk/listSafePayment.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="{% static 'inside/images/favicon.png' %}" rel="icon" type="image/png">

    <!-- Basic Page Needs
    ================================================== -->
    <title>پرداخت امن</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="تریگت - شبکه ی بازار خدمات آنلاین">

{% include "include/header.html" %}


</head>

<body>


    <div id="wrapper">

        {% include "include/sidebar.html" %}

                <div class="main_content">

                    {% include "include/mainHeader.html" %}

                    <div class="container m-auto">
                    {%  include "include/downNavbar.html" %}

                        {% include "include/dashboardHeader.html" %}
                     <div class="my-6 grid   gap-2  uk-link-reset rtl">
                         {% for result in SafePayment %}
                        <div class ="p-3 m-1 rounded-lg bg-white row">
                            <div  class="d-flex">
                            {% if request.user == result.receiver %}
                                {% if result.sender.image %}
                                <div  class="w-10 h-10 m-1 rounded-2xl overflow-hidden"> <img src="{{ result.sender.image.url }}" alt="" class=" rounded-2xl">
                                </div>
                                {% endif %}
                            {% else %}
                                {% if result.receiver.image %}
                                <div  class="w-10 h-10 m-1 rounded-2xl overflow-hidden"> <img src="{{ result.receiver.image.url }}" alt="" class=" rounded-2xl">
                                </div>
                                {% endif %}
                            {% endif %}
                                <div class="p-1">
                                    <p class="irsa"> {% if request.user == result.receiver %}<a href="{% url "main:profile" result.sender.username %}">{{ result.sender.username }}</a>
                                        {% else %}
                                        <a href="{% url "main:profile" result.receiver.username %}">{{ result.receiver.username }}</a>
                                        {% endif %}
                                    </p>
                                <br>
                                    <p class='irsa ]'>
                                       <span class="text-muted">توضیحات:</span> {{ result.description }}
                                    </p>
                                    <p class='irsa '>
                                       <span class="text-muted">قیمت:</span> {{ result.price }}
                                    </p>
                                    <span class="text-xs irsa"> {{ result.createdAdd }} </span>
                                </div>
                            </div>
                                 <div class="d-flex flex-wrap  mt-3">
                                        <br>

                                     <a href="{% url "account:projectManagement" result.pk %}" class="bg-blue-600 flex-fill uk-text-center m-1 p-2 rounded-2xl irsa "><span class="text-white">مدیریت پروژه</span></a>
                                     {% if result.paymentBoolean == True and request.user == result.receiver or result.senderBoolean == True and request.user == result.sender  %}
                                         {% else %}
                                        <a href="{% url "account:SafePaymentAccept" result.pk %}" class="bg-green-500  flex-fill m-1 p-2 uk-text-center rounded-2xl irsa "><span class="text-white">اعلام اتمام کار</span></a>
                                         {% endif %}

                                        {% if result.sender != request.user  and result.paymentBoolean != None %}
                                        {% if result.senderBoolean != True  and result.paymentBoolean != True and result.sender != request.user %}<a href="{% url "account:SafePaymentRefuse" result.pk %}" class="bg-red-400  flex-fill m-1 p-2 uk-text-center rounded-2xl irsa "><span class="text-white">لغو سفارش</span></a>{% endif %}
                                     {% endif %}
                                        <a href="{% if request.user == result.receiver %}{% url "main:profile" result.sender.username %}{% else %}{% url "main:profile" result.receiver.username %}{% endif %}" class="bg-gray-200 flex-fill m-1 p-2 uk-text-center rounded-2xl irsa ">دیدن پروفایل</a>
                                        <a href="{% if request.user == result.receiver %}{% url "account:messageUser" result.sender.username %}{% else %}{% url "account:messageUser" result.receiver.username %}{% endif %}" class="bg-gray-200 flex-fill m-1 p-2 uk-text-center rounded-2xl irsa ">چت</a>
                                        <a href="{% url "account:addDispute" result.pk %}" class="bg-gray-200 flex-fill m-1 p-2 uk-text-center rounded-2xl irsa ">اعلام اختلاف</a>
                                    </div>
                            {% if result.sender == request.user  and result.paymentBoolean == True and result.senderBoolean == False %}
                            <div class="irsa mt-3 p-3 rounded-2xl bg-gray-100">
                                <span class="text-lg">خدمات دهنده اتمام کار را فعال کرده</span> <br>
                            در صورتی که خدمات دهنده کار را به اتمام رسانده شما نیز باید اتمام کار را فعال کنید تا روند تکمیل شود ، در غیر این صورت باید در قسمت اعلام اختلاف مشکل مربوطه را مطرح کنید
                            </div>
                            {% endif %}
                            {% if result.sender == request.user  and result.paymentBoolean == None %}
                            <div class="irsa mt-3 p-3 rounded-2xl bg-gray-100">
                                <span class="text-lg">خدمات دهنده لغو سفارش را انتخاب کرده است است</span> <br>
                            هزینه ای که از کیف پول شما کسر شده است به کف پول شما بازگشته است و میتوانید خرید دیگری انجام دهید
                            </div>
                            {% endif %}
                            {% if result.sender != request.user  and result.senderBoolean == True and result.paymentBoolean == False %}
                            <div class="irsa mt-3 p-3 rounded-2xl bg-gray-100">
                                <span class="text-lg">کارفرما اتمام کار را فعال کرده است است</span> <br>
                            شما نیز باید اتمام کار را بزنید تا روند تکمیل شود
                            </div>
                            {% endif %}

                        </div>
                        {% empty %}
                                {% include "include/empty.html" %}
                        {% endfor %}
                     </div>

                </div>
        </div>
    </div>


    <script>

        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' dark';
            }
        })(window, document);


        (function (window, document, undefined) {

            'use strict';

            // Feature test
            if (!('localStorage' in window)) return;

            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;

            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);

        })(window, document);
    </script>

 <!-- Scripts
    ================================================== -->
    {% include "include/footer.html" %}


</body>



</html>

templates/desk/wallet.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Favicon -->
    <link href="{% static 'inside/images/favicon.png' %}" rel="icon" type="image/png">
    
    <!-- Basic Page Needs
    ================================================== -->
    <title>کیف پول</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="تریگت - شبکه ی بازار خدمات آنلاین">
    {% include "include/header.html" %}


</head>

<body>


    <div id="wrapper">

        {% include "include/sidebar.html" %}

        <div class="main_content">

            {% include "include/mainHeader.html" %}

            <div class="container m-auto"> 
        {%  include "include/downNavbar.html" %}

                {% include "include/dashboardHeader.html" %}
                

                <div class="grid  mt-12 gap-8">
                    {% comment %} <div>
                        <h3 class="text-xl mb-2"> Basic</h3>
                        <p> Lorem ipsum dolor sit amet nibh consectetuer adipiscing elit</p>
                    </div> {% endcomment %}
                    {% if error or success %}
                         <div class="col-span-2 irsa alert alert-warning" role="alert">
                              {{ error }}
                             {{ success }}
                            </div>
                    {% endif %}
                    <div  class="bg-white rounded-md  col-span-2">
                       
                       <div class="rounded-lg grid gap-3 lg:p-6 p-4 bg-gradient-yellow text-white text-bold text-lg">
                            <div class="irsa text-right">
                            اعتبار شما : {{ request.user.cash }}
                            </div>
                       </div>
    
                    </div>
                    <form  method="post" action="{% url 'wallet:increaseMoney' %}" class="bg-white rounded-md  col-span-2">
                        <p class="irsa rtl p-4 rounded-lg bg-light text-bold text-lg">شارژ کیف پول</p>
                       {% csrf_token %}
                       <div class="grid  gap-3 lg:p-6 p-4">
                            <div class="irsa text-right">
                       (به تومان)  مبلغ درخواستی برای افزایش به ریال
                                <input type="number" name="number" min="1">
                            </div>
                           
                       </div>
                        <div class="grid  gap-3 lg:p-6 p-4">
                                <button type="submit" class="irsa btn bg-success text-white" >پرداخت</button>
                            </div>
                    </form>
                    <form  method="post" action="{% url 'wallet:WithdrawMoney' %}" class="bg-white rounded-md  col-span-2">
                       <p class="irsa rtl p-4 rounded-lg bg-light text-bold text-lg">دریافت وجه</p>
                        {% csrf_token %}
                       <div class="grid  gap-3 lg:p-6 p-4">
                            <div class="irsa text-right">
                        (به تومان) مبلغ درخواستی برای دریافت
                                <input type="number" name="number" min="1" max="{{ request.user.cash }}">
                            </div>
                                <div class="irsa text-right">
                         شماره کارت
                                <input type="cardNumber" name="number">
                            </div>
                           <div class="irsa text-right">
                         نام صاحب کارت
                                <input type="name" name="text">
                            </div>

                       </div>
                        <div class="grid  gap-3 lg:p-6 p-4">
                                <button type="submit" class="irsa btn bg-success text-white" >دریافت</button>
                            </div>
                    </form>
                </div>

            </div>
            
        </div>

    </div>




 <!-- Scripts
    ================================================== -->
    {% include "include/footer.html" %}

</body>



</html>